MIBF.hpp
bcgsc/btllib pull request #11
Opened 2021-01-22 01:42 UTC by JackyYiu

2021-01-22 06:38 UTC, schutzekatze requested changes

2021-01-22 06:38 UTC, schutzekatze commented on include/btllib/MIBloomFilter.hpp
> +    const vector<string>& spaced_seeds)
Not sure why this one gives unused parameter. I'd try debugging it by removing parts of the function code and running CI again until you pinpoint the moment when it starts giving the error.

2021-01-22 18:45 UTC, JackyYiu commented on azure-pipelines.yml
> +      sudo apt-get install libsdsl-dev
added `brew install sdsl-lite` in `azure-pipelines.yml`

2021-02-24 01:09 UTC, schutzekatze commented
MIBF is now in master branch.

2021-02-24 01:09 UTC, closed without merging